### ISSUE TITLE
Cannot change the gid of nginx user

### ISSUE THREAD

**Issue by perarg** [tiredofit/docker-nginx-php-fpm#15]
I am trying to change the gid to 1001 as described in Permissions' section of [https://hub.docker.com/r/tiredofit/alpine](). I copy from the documentation:

> If you enable DEBUG_PERMISSIONS=TRUE all the users and groups have been modified in accordance with environment variables will be displayed in output. e.g. If you add USER_NGINX=1000 it will reset the containers nginx user id from 82 to 1000 - Hint, also change the Group ID to your local development users UID & GID and avoid Docker permission issues when developing.

As @tiredofit says at https://github.com/tiredofit/docker-nginx-php-fpm/issues/11#issuecomment-712334578 i tried `ENABLE_PERMISSIONS=TRUE` and comment `# - DEBUG_PERMISSIONS=TRUE`.

I tried every combination i could think but the same result. The gid is "stuck" to 33.

My configuration is the following

```
version: '3.9'
services:
        nginx-php-fpm:
                image: tiredofit/nginx-php-fpm:5.6
                restart: unless-stopped
                container_name: example.com
                volumes:
                - ./html:/www/html
                - ./logs:/www/logs
                environment:
                - VIRTUAL_HOST=example.com
                - VIRTUAL_NETWORK=proxy_default
                - VIRTUAL_PORT=80
                - DEBUG_PERMISSIONS=TRUE
                - ENABLE_PERMISSIONS=TRUE
                - USER_NGINX=1000
                - GROUP_WWW-DATA=1001
networks:
        default:
                external:
                        name: proxy_default
```
