### ISSUE TITLE
Shared folders have 'systemd-resolved' as user:group

### ISSUE THREAD

**Issue by apelliciari** [tiredofit/docker-nginx-php-fpm#3]
Hi,

with a configuration like this

```
version: '3'

services:
  wordpress:
    image: tiredofit/nginx-php-fpm:5.6-latest
    working_dir: /www/html
    volumes:
      - ./wordpress:/www/html

```

on Ubuntu 18.04, the folder "wordpress" and all of its subfolders automatically become owned by 'systemd-resolved'

Why is it happening?

I would like the shared folders to keep the original permissions (like ubuntu:ubuntu)

Thanks
