### ISSUE TITLE
XDebug not enabled in branch 5.6

### ISSUE THREAD

**Issue by apelliciari** [tiredofit/docker-nginx-php-fpm#5]
As reported by phpinfo(), xdebug is not enabled, or am I doing something wrong?

```
services:
  wp:
    image: tiredofit/nginx-php-fpm:5.6-latest
    links:
      - db
    ports:
      - '8000:80'
    environment:
      OPCACHE_MEM_SIZE: 0
      PHP_ENABLE_XDEBUG: 'TRUE'
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
```
