### ISSUE TITLE
Add default index.php file for testing stock image

### ISSUE THREAD

**Issue by radarsymphony** [tiredofit/docker-nginx-php-fpm#53]
**Description of the feature**
Add a default index.php file at /www/html/ for nginx-php-fpm images. Currently when the stock php image is spun up (`tiredofit/nginx-php-fpm:8.1-alpine` freshly pulled for 5day old image), I see a 403 Forbidden page and receive a 403 error code.

Upon inspection, there is no default index file like the one in your nginx image. 
I tested by running `echo "<h1>TESTING</h1>" > /www/html/index.php` inside the container. This then returned a 200 code and helped confirm that the default/stock image was working as expected.

**Benftits of feature**
This feature would make the nginx and nginx-php-fpm a bit more similar and would enable a more streamlined testing process, one that does not require mapping custom assets or using the php image as a base right away. Instead, the image would server a default page and allow quicker prototyping and testing.

**Additional context**

![image](https://github.com/tiredofit/docker-nginx-php-fpm/assets/73671474/a898c85a-2d2f-4f25-849c-1506ccbf30aa)

<details><summary>example compose.yml</summary>

```
services:
  test-php-image:
    #image: tiredofit/nginx-php-fpm:8.1-alpine 
    image: tiredofit/nginx-php-fpm:8.1-alpine-7.5.1 # issue also present 4 months ago
    container_name: test-php-image
    labels:
      - traefik.enable=true
      - traefik.http.routers.test-php-image.rule=Host(`test-php-image.example.com`)
      - traefik.http.services.test-php-image.loadbalancer.server.port=80
    volumes:
      - ./logs:/www/logs
    environment:
      - CONTAINER_NAME=test-php-image
      - DEBUG_MODE=FALSE

        #- NGINX_AUTHENTICATION_TYPE=LLNG
        #- NGINX_AUTHENTICATION_LLNG_ATTRIBUTE1=HTTP_AUTH_USER,uid,upstream_http_uid
        #- NGINX_AUTHENTICATION_LLNG_ATTRIBUTE2=HTTP_AUTH_GROUPS,groups,upstream_http_groups

    networks:
      - services
      - proxy
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
```

</details>
