### ISSUE TITLE
PHP does not read environment variables

### ISSUE THREAD

**Issue by akamalmra** [tiredofit/docker-nginx-php-fpm#67]
PHP does not read environment variables

using docker-compose.yml file:

```
version: '3.7'

services:

  nginx-php-fpm-app:

    image: tiredofit/nginx-php-fpm:8.2-alpine

    volumes:
      - ./html/:/www/html
      - ./logs/:/www/logs
      
    environment:
      - TIMEZONE = Asia/Bahrain
      - PHP_MEMORY_LIMIT = 256M

    ports:
      - 80:80

    restart: always
```

when viewing PHP info both configuration are still showing the default values:

- Default timezone: Etc/GMT
- memory_limit: 128M

Best Regards.
